basePath: /api/v1
definitions:
  dto.ReservationResponse:
    description: 予約情報の詳細
    properties:
      end_time:
        description: |-
          予約終了時間
          @Example "2024-03-20T11:00:00Z"
        example: "2024-03-20T11:00:00Z"
        type: string
      id:
        description: |-
          予約ID
          @Example "rsv_123456"
        example: rsv_123456
        type: string
      start_time:
        description: |-
          予約開始時間
          @Example "2024-03-20T10:00:00Z"
        example: "2024-03-20T10:00:00Z"
        type: string
      status:
        description: |-
          予約ステータス
          @Example "confirmed"
        example: confirmed
        type: string
      user_id:
        description: |-
          ユーザーID
          @Example "user123"
        example: user123
        type: string
    type: object
  presenters.ErrorResponse:
    description: エラー情報のレスポンス
    properties:
      error:
        description: |-
          エラーメッセージ
          @Example "ユーザーIDは必須項目です"
        example: ユーザーIDは必須項目です
        type: string
      status:
        description: |-
          ステータス
          @Example "error"
        example: error
        type: string
    type: object
  presenters.ReservationsResponse:
    description: 予約一覧のレスポンス
    properties:
      data:
        description: 予約データ
        items:
          $ref: '#/definitions/dto.ReservationResponse'
        type: array
      status:
        description: |-
          ステータス
          @Example "success"
        example: success
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 予約管理システムのRESTful API
  title: 予約管理システム API
  version: "1.0"
paths:
  /reservations:
    get:
      consumes:
      - application/json
      description: 指定されたユーザーIDに紐づく予約の一覧を取得します
      parameters:
      - description: ユーザーID
        in: query
        maxLength: 50
        minLength: 3
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenters.ReservationsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presenters.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenters.ErrorResponse'
      summary: ユーザーの予約一覧を取得
      tags:
      - reservations
swagger: "2.0"
