basePath: /api/v1.
definitions:
  dto.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.LoginResponse:
    properties:
      access_token:
        type: string
      expires_at:
        type: integer
    type: object
  dto.PlanResponse:
    description: プラン情報の詳細.
    properties:
      description:
        description: |-
          プランの説明
          @Example "基本的なサービスが含まれるプランです"
        example: 基本的なサービスが含まれるプランです
        type: string
      duration:
        description: |-
          プランの期間（日数）
          @Example 30
        example: 30
        type: integer
      id:
        description: |-
          プランID
          @Example "plan123"
        example: plan123
        type: string
      name:
        description: |-
          プラン名
          @Example "スタンダードプラン"
        example: スタンダードプラン
        type: string
      price:
        description: |-
          プランの価格
          @Example 1000
        example: 1000
        type: integer
    type: object
  dto.ReservationResponse:
    description: 予約情報の詳細.
    properties:
      end_time:
        description: |-
          予約終了時間
          @Example "2024-03-20T11:00:00Z"
        example: "2024-03-20T11:00:00Z"
        type: string
      id:
        description: |-
          予約ID
          @Example "rsv_123456"
        example: rsv_123456
        type: string
      plan:
        allOf:
        - $ref: '#/definitions/dto.PlanResponse'
        description: |-
          プラン情報
          @Example {"id": "plan123", "name": "スタンダードプラン"}
      start_time:
        description: |-
          予約開始時間
          @Example "2024-03-20T10:00:00Z"
        example: "2024-03-20T10:00:00Z"
        type: string
      status:
        description: |-
          予約ステータス
          @Example "confirmed"
        example: confirmed
        type: string
      user:
        allOf:
        - $ref: '#/definitions/dto.UserResponse'
        description: |-
          ユーザー情報
          @Example {"id": "user123", "name": "山田太郎"}
      user_id:
        description: |-
          ユーザーID
          @Example "user123"
        example: user123
        type: string
    type: object
  dto.UserResponse:
    description: ユーザー情報の詳細.
    properties:
      email:
        description: |-
          メールアドレス
          @Example "taro.yamada@example.com"
        example: taro.yamada@example.com
        type: string
      id:
        description: |-
          ユーザーID
          @Example "user123"
        example: user123
        type: string
      name:
        description: |-
          ユーザー名
          @Example "山田太郎"
        example: 山田太郎
        type: string
      phone:
        description: |-
          電話番号
          @Example "090-1234-5678"
        example: 090-1234-5678
        type: string
    type: object
  presenters.LoginResponse:
    description: ログイン処理のレスポンス.
    properties:
      data:
        allOf:
        - $ref: '#/definitions/dto.LoginResponse'
        description: ログインデータ
      status:
        description: |-
          ステータス
          @Example "success"
        example: success
        type: string
    type: object
  presenters.PlansResponse:
    description: プラン一覧のレスポンス.
    properties:
      data:
        description: プランデータ
        items:
          $ref: '#/definitions/dto.PlanResponse'
        type: array
      status:
        description: |-
          ステータス
          @Example "success"
        example: success
        type: string
    type: object
  presenters.PresentError:
    properties:
      message:
        type: string
    type: object
  presenters.ReservationsResponse:
    description: 予約一覧のレスポンス.
    properties:
      data:
        description: 予約データ
        items:
          $ref: '#/definitions/dto.ReservationResponse'
        type: array
      status:
        description: |-
          ステータス
          @Example "success"
        example: success
        type: string
    type: object
  response.ErrorResponse:
    description: エラー情報のレスポンス.
    properties:
      error:
        description: |-
          エラーメッセージ
          @Example "プランが見つかりません"
        example: プランが見つかりません
        type: string
      status:
        description: |-
          ステータス
          @Example "error"
        example: error
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 予約管理システムのRESTful API
  title: 予約管理システム API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: ユーザー名とパスワードを使用してログイン認証を行います
      parameters:
      - description: ログイン情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ログイン成功時のレスポンス
          schema:
            $ref: '#/definitions/presenters.LoginResponse'
        "400":
          description: リクエストの形式が不正
          schema:
            $ref: '#/definitions/presenters.PresentError'
        "401":
          description: パスワードが一致しない
          schema:
            $ref: '#/definitions/presenters.PresentError'
        "500":
          description: サーバー内部エラー
          schema:
            $ref: '#/definitions/presenters.PresentError'
      summary: ユーザーログイン
      tags:
      - auth
  /plans:
    get:
      consumes:
      - application/json
      description: 指定されたユーザーIDに関連するプラン一覧を取得します
      parameters:
      - description: ユーザーID
        in: header
        name: X-User-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenters.PlansResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: プラン一覧取得
      tags:
      - plans
  /reservations:
    get:
      consumes:
      - application/json
      description: 指定されたユーザーIDに紐づく予約の一覧を取得します
      parameters:
      - description: ユーザーID
        in: query
        maxLength: 50
        minLength: 3
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenters.ReservationsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: ユーザーの予約一覧を取得
      tags:
      - reservations
swagger: "2.0"
